from pathlib import Path
import json, re
R=Path(r'.')
readj=lambda p:json.loads((R/p).read_text(encoding='utf-8-sig'))
audit=readj('reviews/refactor-audit.json');original=readj('reviews/original-portfolio.json')
meta={m['slug']:m for f in (R/'reviews').glob('author-*.json') if (m:=json.loads(f.read_text(encoding='utf-8-sig')))}
w=R/'chapters/wizard.md';t=w.read_text(encoding='utf-8')
t=t.replace('The refactor does not silently patch the source library; it constrains stage use and identifies when the template is the wrong tool.','The initial candidate tried to address this through author-stage constraints alone. Independent review showed that saved-value fallback made those constraints insufficient. The final port repairs required input handling in the shared helper, while retaining stage validation for supported values and terminal availability.')
t=t.replace('The helper is copied unchanged in this compendium. It was read completely but not executed during authoring. No claim is made that live dashboard navigation, credential storage, or CI integration has been tested. This preservation makes the comparison honest: the refactor changes the instructions and supported contract, not a secretly rewritten helper.','The initial helper is preserved under evals/candidate-v1/wizard. The final candidate repairs EOF, empty required input, failed remote-write status, and the completion headline. Isolated Bash fixtures exercised source, initial candidate and repair: the source and initial candidate met 4 of 14 selected checks; the repair met all 14. These are targeted regression checks after a known defect, not independent benchmark evidence. Live dashboards, real credential storage, and CI integration were not exercised. [Read the executed checks](../evals/WIZARD-REPAIR.md).')
t=t.replace('When the unchanged template fits,','When the supplied repaired template fits,')
t=t.replace('**D2: Declare unchanged helper limitations and validate supported values in generated stages.**','**D2: Declare remaining helper limitations and validate supported values in generated stages.**')
t=t.replace('gh infers context and the template\'s skipped operations can coexist with a completion banner.','gh infers context; the source could display completion after skipped operations. The final helper returns failure and displays incomplete when required operations fail.')
t=t.replace('- template.sh: **copy** — Preserve helper library unchanged; document its supported bare single-line env values, EOF limitations, GitHub target assumptions, and author-stage validation requirements instead of claiming universal safety.','- template.sh: **repair** — Preserve the small shared library while making EOF and empty required input fail, returning nonzero for failed remote writes, and reporting incomplete when skips remain. Bare-value serialization and target identity still require explicit stage validation.')
w.write_text(t,encoding='utf-8')
m=meta['wizard'];m['summary']='Preserve the staged human-run procedure, repair input and completion handling in the shared helper, and make remaining storage and destination limits explicit.'
for x in m['supporting_disposition']:
 if x['file']=='template.sh':x.update(action='repair',reason='Repair EOF, empty required input, remote failure status and incomplete summary; retain constrained serialization and explicit target validation.')
for d in m['deltas']:
 if d['id']=='D2':d['change']='Declare remaining helper limitations and validate supported values in generated stages.'
 if d['id']=='D3':d['reason']='gh infers context; repaired helpers now return nonzero for failed writes and report incomplete when skips remain.'
if not any(d['id']=='D6' for d in m['deltas']):m['deltas'].append(dict(id='D6',change='Repair the executable helper, not only its authoring instructions.',reason='An unchanged helper could reuse saved input after EOF and report completion despite failed required writes.',tradeoff='The port now owns a small maintained Bash delta; 14 isolated regression fixtures cover the changed contract.'))
m=meta['triage']
if not any(d['id']=='AUDIT-CLOSURE' for d in m['deltas']):m['deltas'].append(dict(id='AUDIT-CLOSURE',change='Restore closure for all authorized wontfix dispositions, with an explicit label-only exception.',reason='The initial candidate accidentally omitted the source terminal action for some reasons.',tradeoff='Execution still depends on tracker access and the authorized scope.'))
m=meta['setup-matt-pocock-skills']
for x in m['supporting_disposition']:
 if x['file']=='issue-tracker-local.md':x.update(action='repair',reason='Provide a new-tracker seed while explicitly giving the observed existing tracker schema priority, including single-file trackers.')
if not any(d['id']=='TRIAL-SEED' for d in m['deltas']):m['deltas'].append(dict(id='TRIAL-SEED',change='Make existing tracker conventions override the example seed in both entrypoint and support file.',reason='The first response trial invented an uninspected layout despite a preservation instruction.',tradeoff='Missing schema details remain explicit until inspected; a seed cannot fill them in as facts.'))
for slug,m in meta.items():
 m['evaluation_status']='recorded-v1-with-versioned-repairs' if slug in ['wizard','triage','setup-matt-pocock-skills'] else 'recorded-development-trials'
 (R/'reviews'/('author-'+slug+'.json')).write_text(json.dumps(m,indent=2),encoding='utf-8')
def locators(items):
 out=[]
 for s in items:
  z=re.match(r'^(.*?):(\d+)(?:-(\d+))?$',s)
  if z:out.append(f'[{s}](../{z[1]})')
  else:out.append(s)
 return ', '.join(out)
for slug,m in meta.items():
 p=R/'chapters'/(slug+'.md');t=p.read_text(encoding='utf-8')
 t=t.replace('is pending at authorship. Its actual run record, when present, takes precedence over predictions in this chapter.','contains the recorded trial responses and judgments. That run record takes precedence over predictions in this chapter.')
 t=t.replace('Independent evaluation is pending until the linked report records an actual run. No behavioral score is claimed in this chapter.','The linked independent evaluation records the actual text responses, case-bound grades and limitations. The design bet in this chapter is distinct from those observations.')
 t=t.replace('was **pending at authoring**. The bet above is a hypothesis, not an observed score. Judge the eventual trial on decisions, outputs, and failure recovery; tidy formatting alone cannot establish improvement.','now records the trial responses and case-bound grades. The bet above remains a design hypothesis, not a demonstrated collaboration gain. Judge the recorded trial on the behavior it actually tested; tidy formatting alone cannot establish improvement.')
 t=t.split('\n<!-- INDEPENDENT-AUDIT -->')[0].rstrip()
 a=next(x for x in audit['reviews'] if x['slug']==slug);o=next(x for x in original['reviews'] if x['source_slug']==slug)
 block='\n\n<!-- INDEPENDENT-AUDIT -->\n## Independent scrutiny\n\n'
 block+=f"The semantic reviewer read the source and candidate independently of this chapter and its author bet. Initial verdict: **{a['verdict']}**. {a['finding']}\n\n{a['recommended_change']}\n\nEvidence: {locators(a['source_evidence'])}; {locators(a['candidate_evidence'])}. This is static inspection, not proof of a completed workflow.\n\n"
 if slug=='wizard':block+='**Repair and retest:** the final shared template now enforces the missing input/failure/completion contract. [Fourteen isolated regression checks](../evals/WIZARD-REPAIR.md) pass on the repair. The initial text-trial grade applies to the archived candidate; the repair has separate evidence. The remaining raw dotenv serializer and inferred GitHub target are still limits requiring stage validation.\n\n'
 if slug=='triage':block+='**Repair:** the candidate now explicitly closes all authorized wontfix dispositions, while an explicit label-only request remains label-only. The initial text-trial grade applies to the archived candidate. [Targeted follow-up probes](../evals/FOLLOWUP-RESULTS.md) cover both scopes; they are response evidence, not executed tracker changes.\n\n'
 if slug=='setup-matt-pocock-skills':block+='**Additional trial finding and repair:** although static inspection found no material defect, the initial response imposed the example tracker layout on an unspecified existing tracker. The final entrypoint and local seed now explicitly give observed conventions priority, including an existing single-file tracker. The original lower grade remains recorded. [Targeted follow-up evidence](../evals/FOLLOWUP-RESULTS.md) checks a concrete existing schema; no live configuration was written.\n\n'
 if slug=='writing-beats':block+='**Observed response miss:** the first candidate response correctly removed unemployment but assumed other story facts not supplied by its stress case. Its grade remains lower than the source for that case. Cases shared context, making cross-case carryover a plausible explanation rather than an established cause. The instructions already prohibit invented prerequisites, so they were not lengthened solely to target this fixture. [A fresh targeted retest](../evals/FOLLOWUP-RESULTS.md) supplies no other story facts; it does not erase the first result.\n\n'
 block+=f"### Scrutiny of the original proposal\n\nThe independent portfolio reviewer read the proposed skill without this chapter's advocacy. Initial verdict for **{o['original_slug']}**: **{o['verdict']}**. “Pilot” means worth a bounded test; it does not mean proven or selected for installation.\n\n{o['strength']} {o['distinctness']}\n\n**Weakness:** {o['weakness']}\n\n**Suggested improvement:** {o['recommended_change']}\n\nA proposed test was: {o['example_prompt']} Success would mean: {o['success_criterion']} This is a test proposal, not an observed outcome.\n\n"
 if slug in ['grill-me','writing-fragments']:block+=f"**Current replacement:** this chapter now proposes **{m['original_slug']}**. The overlapping initial proposal is archived. Read [the replacement record](../reviews/original-revisions.json), [current independent design review](../reviews/original-followup.json), and [actual targeted responses](../evals/FOLLOWUP-RESULTS.md).\n\n"
 if slug=='retro':block+='**Repair to instruction-ablation:** a fresh context does not ensure a clean absent condition. The skill now requires checking inherited and equivalent rules; an unavoidable duplicate rule makes the feasible experiment a comparison of incremental wording. A null contrast cannot show that the underlying behavior requirement is useless. [Current review](../reviews/original-followup.json) and [targeted probe](../evals/FOLLOWUP-RESULTS.md).\n\n'
 if slug=='writing-shape':block+='**Repair to thesis-stress-test:** the final challenge now follows the kind of claim. Empirical claims invite counterevidence; normative claims invite competing values or unacceptable implications; personal reports invite fidelity and scope checks; metaphors invite questions about explanatory use and limits. The skill no longer requires every thesis to become an empirically falsifiable prediction. [Current review](../reviews/original-followup.json) and [targeted probe](../evals/FOLLOWUP-RESULTS.md).\n\n'
 block+='The full [refactor audit](../reviews/refactor-audit.json) and [initial original-portfolio review](../reviews/original-portfolio.json) preserve the independent record. No proposal inherits effectiveness from having passed a structural check.\n'
 p.write_text(t+block,encoding='utf-8')
summary='# Independent reviews and revisions\n\nTwo agents inspected the complete collection independently of the chapter advocacy. One compared all 38 source/refactor packages and support files; the other read all 38 original proposals. These were design reviews, not live workflow tests.\n\n'
summary+='The initial semantic audit found **31 clear, 5 deliberate tradeoffs, and 2 repairs**. Both repairs were implemented with the initial candidates preserved: triage regains authorized closure; wizard fixes required-input and completion behavior. The [wizard regression results](evals/WIZARD-REPAIR.md) distinguish the repaired helper from the text trial of its first version.\n\n'
summary+='The response trial found a third concrete repair: the setup seed could override an existing tracker layout. Its final text gives observed conventions priority and receives a targeted follow-up. Writing-beats also lost partial credit for unsupplied story assumptions; its unchanged instructions receive an isolated retest, while the original score remains visible.\n\n'
summary+='The original-portfolio audit recommended **26 pilots, 8 merges, 2 repairs, and 2 deferrals**. This is a useful challenge to the idea that 38 proposals should mean 38 installations. Two overlapping proposals were replaced with preference-probes and anchored-variation. Instruction-ablation and thesis-stress-test received consequential validity repairs. The remaining merge/defer judgments remain visible in each chapter rather than being edited into universal praise.\n\n'
summary+='## Portfolio judgment\n\n'+ '\n\n'.join(original['portfolio_observations'][1:])+'\n\n## Retained records\n\n- [Initial semantic audit](reviews/refactor-audit.json)\n- [Initial original proposal audit](reviews/original-portfolio.json)\n- [Current original revisions review](reviews/original-followup.json)\n- [Versioned repair hashes](reviews/audit-repairs.json)\n- [Replacement proposal history](reviews/original-revisions.json)\n- [Targeted follow-up responses](evals/FOLLOWUP-RESULTS.md)\n'
(R/'REVIEWS.md').write_text(summary,encoding='utf-8')
print('Integrated independent review into all 38 chapters; repaired stale wizard claims.')
