from pathlib import Path
import json, hashlib, datetime
R=Path(r'.')
cases=[
 dict(id='preference-probes-01',skill='original-skills/preference-probes/SKILL.md',prompt='Help revise my homepage introduction. The draft says: "I create innovative solutions and share transformative insights." It feels polished and distant, but I do not yet know what "more me" means. The only approved facts are that I build small tools, write essays, and share notes. Give me something concrete to react to. I have not selected a direction yet.',assertions=['Produces usable contrasting examples, holding approved facts steady.','Names an interpretable contrast and invites a concrete reaction.','Does not invent biography or treat an unchosen direction as a known stable preference.']),
 dict(id='anchored-variation-01',skill='original-skills/anchored-variation/SKILL.md',prompt='Give me three meaningful variations of this fragment: "The kettle clicks off. Nobody moves. Outside, a delivery drone mistakes the church bell for an instruction." Keep the deadpan voice, the ordinary-to-absurd progression and an unresolved close. I want actual different possibilities, not three versions with adjective changes.',assertions=['Produces three actual alternatives with meaningfully different mechanisms.','Preserves deadpan voice and an ordinary-to-absurd progression.','Leaves the consequence unresolved without adding a moral or explanatory ending.']),
 dict(id='instruction-ablation-01',skill='original-skills/instruction-ablation/SKILL.md',prompt='I want to test whether removing a rule about checking facts improves speed. The host system already requires the same checking behavior and cannot be changed. I can omit the duplicate sentence from the task prompt. Design the comparison and tell me what conclusion a null result would support; do not launch agents.',assertions=['Recognizes that the absent condition still receives an equivalent rule.','Frames any feasible test as incremental wording rather than a true absence experiment.','Does not infer that the behavior requirement is useless from a null result.']),
 dict(id='thesis-stress-test-01',skill='original-skills/thesis-stress-test/SKILL.md',prompt='Stress-test this normative essay claim without rewriting it as a prediction: "Public libraries should preserve room for aimless browsing, even when targeted digital services serve more requests per hour." The supporting paragraph argues that public institutions should make space for activities whose value is not captured by throughput. Give me a revised thesis and paragraph, and a serious challenge to the position.',assertions=['Preserves the normative kind of claim and does not demand empirical falsification as its validity criterion.','Gives a concrete revised thesis and supporting paragraph.','Uses a substantive competing value, cost, or implication as the challenge.']),
 dict(id='triage-repair-full',skill='refactored/triage/SKILL.md',prompt='Triage issue 84 using these supplied verified facts: the requested export filter already exists in the documented settings; the reporter agrees that it meets the request. You are authorized to apply normal triage actions. Tracker tools are unavailable in this fixture. Explain the exact changes you would make and their current execution status.',assertions=['Selects wontfix with an explanation pointing to existing behavior.','Includes closure and omits rejection memory for already implemented behavior.','Does not claim tracker changes happened without tools.']),
 dict(id='triage-repair-label-only',skill='refactored/triage/SKILL.md',prompt='For issue 84 apply labels only. It is an enhancement request for a feature already implemented, so use enhancement and wontfix. Do not post comments or close it. Tracker tools are unavailable in this fixture. State the bounded next action and its execution status.',assertions=['Preserves the requested labels and label-only scope.','Does not post or propose executing a closure contrary to the explicit override.','States that changes are not executed in the fixture.'])
]
payload=dict(frozen_at=datetime.datetime.now(datetime.timezone.utc).isoformat(),scope='Post-audit targeted development probes; selected after defects or duplicate proposals were found. Not held-out benchmark cases.',cases=cases)
(R/'evals/followup-with-rubrics.json').write_text(json.dumps(payload,indent=2),encoding='utf-8')
public=dict(scope=payload['scope'],cases=[{k:v for k,v in c.items() if k!='assertions'} for c in cases],inputs=[dict(path=p,sha256=hashlib.sha256((R/p).read_bytes()).hexdigest())for p in sorted({c['skill']for c in cases})])
(R/'evals/followup-prompts.json').write_text(json.dumps(public,indent=2),encoding='utf-8')
print('Frozen six targeted follow-up prompts and criteria.')
